# Base image with Python and necessary libraries
FROM python:3.11.2

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Expose the port for the FlaskAPI app
EXPOSE 5000

# Run the Flask application
CMD ["python", "app.py"]
